project:
  type: book
  output-dir: _book

book:
  title: "Matemática para Gañanes y Patanes"
  subtitle: "Matemática y conocimiento profesional para la enseñanza"
  chapters:
    - index.qmd
    - acerca.qmd
    - part: contenidos/libro/index.qmd
      chapters:
        - contenidos/libro/numeros/porcentajes.qmd
        - contenidos/libro/probabilidad/combinatoria-probabilidad.qmd
        - contenidos/libro/estadistica/index.qmd
        - contenidos/libro/algebra/potencias-raices-logaritmos.qmd
        - contenidos/libro/algebra/algebra-elemental.qmd
        - contenidos/libro/algebra/ecuaciones-inecuaciones.qmd
        - contenidos/libro/algebra/sucesiones-series.qmd
        - contenidos/libro/algebra/funciones.qmd
    - part: contenidos/curriculo-evaluacion.qmd
      chapters:
        - contenidos/curriculum/index.qmd
        - contenidos/paes/index.qmd

format:
  pdf:
    documentclass: scrreprt
    toc: true
    filters:
      - filters/paes-question.lua
      - filters/knowledge.lua
