---
title: "3.3 Enseñanza básica, ciclo I"
description: "Objetivos de aprendizaje de Matemática de primero a cuarto básico."
number-sections: false
toc: true
toc-depth: 3
---

# 3.3 Enseñanza básica, ciclo I {.unnumbered}

## 3.3.1 Primero básico

### Números y operaciones

1. **OA 1.** Contar números del 0 al 100 de 1 en 1, de 2 en 2, de 5 en 5 y de 10 en 10, hacia adelante y hacia atrás, empezando por cualquier número menor que 100.

2. **OA 2.** Identificar el orden de los elementos de una serie, utilizando números ordinales del primero (1ro) al décimo (10mo).

3. **OA 3.** [Prioritario]{.change-badge .change-priority} Leer números del 0 al 20 y representarlos en forma concreta, pictórica y simbólica.

4. **OA 4.** [Prioritario]{.change-badge .change-priority} Comparar y ordenar números del 0 al 20 de menor a mayor y/o viceversa, utilizando material concreto y/o usando *software* educativo.

5. **OA 5.** Estimar cantidades hasta 20 en situaciones concretas, usando un referente.

6. **OA 6.** [Prioritario]{.change-badge .change-priority} Componer y descomponer números del 0 al 20 de manera aditiva, en forma concreta, pictórica y simbólica.

7. **OA 7.** Describir y aplicar estrategias de cálculo mental para las adiciones y sustracciones hasta 20:

    - conteo hacia adelante y atrás

    - completas 10

    - dobles

8. **OA 8.** [Prioritario]{.change-badge .change-priority} Determinar las unidades y decenas en números del 0 al 20, agrupando de a 10, de manera concreta, pictórica y simbólica.

9. **OA 9.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la adición y la sustracción de números del 0 al 20 progresivamente, de 0 a 5, de 6 a 10, de 11 a 20 con dos sumandos:

    - usando un lenguaje cotidiano para describir acciones desde su propia experiencia

    - representando adiciones y sustracciones con material concreto y pictórico, de manera manual y/o usando *software* educativo

    - representando el proceso en forma simbólica

    - resolviendo problemas en contextos familiares

    - creando problemas matemáticos y resolviéndolos

10. **OA 10.** Demostrar que la adición y la sustracción son operaciones inversas, de manera concreta, pictórica y simbólica.

### Patrones y álgebra

11. **OA 11.** [Prioritario]{.change-badge .change-priority} Reconocer, describir, crear y continuar patrones repetitivos (sonidos, figuras, ritmos, ...) y patrones numéricos hasta el 20, crecientes y decrecientes, usando material concreto, pictórico y simbólico, de manera manual y/o por medio de *software* educativo.

12. **OA 12.** Describir y registrar la igualdad y la desigualdad como equilibrio y desequilibrio, usando una balanza en forma concreta, pictórica y simbólica del 0 al 20, usando el símbolo igual ($=$).

### Geometría

13. **OA 13.** [Prioritario]{.change-badge .change-priority} Describir la posición de objetos y personas con relación a sí mismos y a otros objetos y personas, usando un lenguaje común (como derecha e izquierda).

14. **OA 14.** [Prioritario]{.change-badge .change-priority} Identificar en el entorno figuras 3D y figuras 2D y relacionarlas, usando material concreto.

15. **OA 15.** Identificar y dibujar líneas rectas y curvas.

### Medición

16. **OA 16.** Usar unidades no estandarizadas de tiempo para comparar la duración de eventos cotidianos.

17. **OA 17.** Usar un lenguaje cotidiano para secuenciar eventos en el tiempo: días de la semana, meses del año y algunas fechas significativas.

18. **OA 18.** [Prioritario]{.change-badge .change-priority} Identificar y comparar la longitud de objetos, usando palabras como largo y corto.

### Datos y probabilidades

19. **OA 19.** [Prioritario]{.change-badge .change-priority} Recolectar y registrar datos para responder preguntas estadísticas sobre sí mismo y el entorno, usando bloques, tablas de conteo y pictogramas.

20. **OA 20.** [Prioritario]{.change-badge .change-priority} Construir, leer e interpretar pictogramas.

## 3.3.2 Segundo básico

### Números y operaciones

1. **OA 1.** Contar números del 0 al 1000 de 2 en 2, de 5 en 5, de 10 en 10 y de 100 en 100, hacia adelante y hacia atrás, empezando por cualquier número menor que 1000.

2. **OA 2.** [Prioritario]{.change-badge .change-priority} Leer números del 0 al 100 y representarlos en forma concreta, pictórica y simbólica.

3. **OA 3.** [Prioritario]{.change-badge .change-priority} Comparar y ordenar números del 0 al 100 de menor a mayor y viceversa, usando material concreto y monedas nacionales de manera manual y/o por medio de software educativo.

4. **OA 4.** Estimar cantidades hasta 100 en situaciones concretas, usando un referente.

5. **OA 5.** [Prioritario]{.change-badge .change-priority} Componer y descomponer números del 0 a 100 de manera aditiva, en forma concreta, pictórica y simbólica.

6. **OA 6.** Describir y aplicar estrategias de cálculo mental para adiciones y sustracciones hasta 20:

    - completar 10

    - usar dobles y mitades

    - “uno más uno menos”

    - “dos más dos menos”

    - usar la reversibilidad de las operaciones

7. **OA 7.** [Prioritario]{.change-badge .change-priority} Identificar las unidades y decenas en números del 0 al 100, representando las cantidades de acuerdo a su valor posicional, con material concreto, pictórico y simbólico.

8. **OA 8.** Demostrar y explicar de manera concreta, pictórica y simbólica el efecto de sumar y restar 0 a un número.

9. **OA 9.** [Prioritario]{.change-badge .change-priority} Demostrar que comprende la adición y la sustracción en el ámbito del 0 al 100:

    - usando un lenguaje cotidiano y matemático para describir acciones desde su propia experiencia

    - resolviendo problemas con una variedad de representaciones concretas y pictóricas, de manera manual y/o usando *software* educativo

    - registrando el proceso en forma simbólica

    - aplicando los resultados de las adiciones y las sustracciones de los números del 0 a 20 sin realizar cálculos

    - aplicando el algoritmo de la adición y la sustracción sin considerar reserva

    - creando problemas matemáticos en contextos familiares y resolviéndolos

10. **OA 10.** [Prioritario]{.change-badge .change-priority} Demostrar que comprende la relación entre la adición y la sustracción al usar la “familia de operaciones” en cálculos aritméticos y la resolución de problemas

11. **OA 11.** [Prioritario]{.change-badge .change-priority} Demostrar que comprende la multiplicación:

    - usando representaciones concretas y pictóricas

    - expresando una multiplicación como una adición de sumandos iguales

    - usando la distributividad como estrategia para construir las tablas del 2, del 5 y del 10

    - resolviendo problemas que involucren las tablas del 2, del 5 y del 10.

### Patrones y álgebra

12. **OA 12.** [Prioritario]{.change-badge .change-priority} Crear, representar y continuar una variedad de patrones numéricos y completar los elementos faltantes, de manera manual y/o usando *software* educativo.

13. **OA 13.** [Prioritario]{.change-badge .change-priority} Demostrar, explicar y registrar la igualdad y la desigualdad en forma concreta y pictórica del 0 al 20, usando el símbolo igual ($=$) y los símbolos no igual ($>$, $<$).

### Geometría

14. **OA 14.** Representar y describir la posición de objetos y personas con relación a sí mismos y a otros objetos y personas, incluyendo derecha e izquierda y usando material concreto y dibujos.

15. **OA 15.** [Prioritario]{.change-badge .change-priority} Describir, comparar y construir figuras 2D (triángulos, cuadrados, rectángulos y círculos) con material concreto.

16. **OA 16.** [Prioritario]{.change-badge .change-priority} Describir, comparar y construir figuras 3D (cubos, paralelepípedos, esferas y conos) con diversos materiales.

### Medición

17. **OA 17.** Identificar días, semanas, meses y fechas en el calendario.

18. **OA 18.** Leer horas y medias horas en relojes digitales, en el contexto de la resolución de problemas.

19. **OA 19.** [Prioritario]{.change-badge .change-priority} Determinar la longitud de objetos, usando unidades de medidas no estandarizadas y unidades estandarizadas (cm y m), en el contexto de la resolución de problemas.

### Datos y probabilidades

20. **OA 20.** [Prioritario]{.change-badge .change-priority} Recolectar y registrar datos para responder preguntas estadísticas sobre juegos con monedas y dados, usando bloques y tablas de conteo y pictogramas.

21. **OA 21.** Registrar en tablas y gráficos de barra simple, resultados de juegos aleatorios con dados y monedas.

22. **OA 22.** [Prioritario]{.change-badge .change-priority} Construir, leer e interpretar pictogramas con escala y gráficos de barra simple.

## 3.3.3 Tercero básico

### Números y operaciones

1. **OA 1.** Contar números del 0 al 1000 de 5 en 5, de 10 en 10, de 100 en 100:

    - empezando por cualquier número natural menor que 1000

    - de 3 en 3, de 4 en 4..., empezando por cualquier múltiplo del número correspondiente

2. **OA 2.** [Prioritario]{.change-badge .change-priority} Leer números hasta 1.000 y representarlos en forma concreta, pictórica y simbólica.

3. **OA 3.** [Prioritario]{.change-badge .change-priority} Comparar y ordenar números naturales hasta 1000, utilizando la recta numérica o la tabla posicional de manera manual y/o por medio de *software* educativo.

4. **OA 4.** Describir y aplicar estrategias de cálculo mental para las adiciones y las sustracciones hasta 100:

    - por descomposición

    - completar hasta la decena más cercana

    - usar dobles

    - sumar en vez de restar

    - aplicar la asociatividad

5. **OA 5.** [Prioritario]{.change-badge .change-priority} Identificar y describir las unidades, las decenas y las centenas en números del 0 al 1000, representando las cantidades de acuerdo a su valor posicional, con material concreto, pictórico y simbólico.

6. **OA 6.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la adición y la sustracción de números del 0 al 1000:

    - usando estrategias personales con y sin material concreto

    - creando y resolviendo problemas de adición y sustracción que involucren operaciones combinadas, en forma concreta, pictórica y simbólica, de manera manual y/o por medio de *software* educativo

    - aplicando los algoritmos con y sin reserva, progresivamente, en la adición de hasta cuatro sumandos y en la sustracción de hasta un sustraendo

7. **OA 7.** Demostrar que comprenden la relación entre la adición y la sustracción, usando la “familia de operaciones” en cálculos aritméticos y en la resolución de problemas.

8. **OA 8.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden las tablas de multiplicar hasta el 10 de manera progresiva:

    1.  usando representaciones concretas y pictóricas

    2.  expresando una multiplicación como una adición de sumandos iguales

    3.  usando la distributividad como estrategia para construir las tablas hasta el 10

    4.  aplicando los resultados de las tablas de multiplicación hasta $10\cdot 10$, sin realizar cálculos

    5.  resolviendo problemas que involucren las tablas aprendidas hasta el 10

9. **OA 9.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la división en el contexto de las tablas de hasta $10\cdot 10$:

    1.  representando y explicando la división como repartición y agrupación en partes iguales, con material concreto y pictórico

    2.  creando y resolviendo problemas en contextos que incluyan la repartición y la agrupación

    3.  expresando la división como una sustracción repetida

    4.  describiendo y aplicando la relación inversa entre la división y la multiplicación

    5.  aplicando los resultados de las tablas de multiplicación hasta $10\cdot 10$, sin realizar cálculos

10. **OA 10.** [Prioritario]{.change-badge .change-priority} Resolver problemas rutinarios en contextos cotidianos, que incluyan dinero e involucren las cuatro operaciones (no combinadas).

11. **OA 11.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden las fracciones de uso común: $\frac{1}{4}, \frac{1}{3}, \frac{1}{2}, \frac{2}{3}, \frac{3}{4}$:

    - explicando que una fracción representa la parte de un todo, de manera concreta, pictórica, simbólica, de forma manual y/o con *software* educativo

    - describiendo situaciones en las cuales se puede usar fracciones

    - comparando fracciones de un mismo todo, de igual denominador

### Patrones y álgebra

12. **OA 12.** [Prioritario]{.change-badge .change-priority} Generar, describir y registrar patrones numéricos, usando una variedad de estrategias en tablas del 100, de manera manual y/o con software educativo.

13. **OA 13.** Resolver ecuaciones de un paso que involucren adiciones y sustracciones y un símbolo geométrico que represente un número desconocido, en forma pictórica y simbólica del 0 al 100.

### Geometría

14. **OA 14.** Describir la localización de un objeto en un mapa simple o en una cuadrícula.

15. **OA 15.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la relación que existe entre figuras 3D y figuras 2D:

    1.  construyendo una figura 3D a partir de una red (plantilla)

    2.  desplegando la figura 3D

16. **OA 16.** Describir cubos, paralelepípedos, esferas, conos, cilindros y pirámides de acuerdo a la forma de sus caras y el número de aristas y vértices.

17. **OA 17.** Reconocer en el entorno figuras 2D que están trasladadas, reflejadas y rotadas.

18. **OA 18.** Demostrar que comprenden el concepto de ángulo:

    1.  identificando ejemplos de ángulos en el entorno

    2.  estimando la medida de ángulos, usando como referente ángulos de $45^\circ$ y de $90^\circ$

### Medición

19. **OA 19.** Leer e interpretar líneas de tiempo y calendarios.

20. **OA 20.** Leer y registrar el tiempo en horas, medias horas, cuartos de hora y minutos en relojes análogos y digitales.

21. **OA 21.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden el perímetro de una figura regular e irregular:

    1.  midiendo y registrando el perímetro de figuras del entorno en el contexto de la resolución de problemas

    2.  determinando el perímetro de un cuadrado y de un rectángulo

22. **OA 22.** [Prioritario]{.change-badge .change-priority} Demostrar que comprende la medición del peso (g y kg):

    1.  comparando y ordenando dos o más objetos a partir de su peso de manera informal

    2.  usando modelos para explicar la relación que existe entre gramos y kilogramos

    3.  estimando el peso de objetos de uso cotidiano, usando referentes

    4.  midiendo y registrando el peso de objetos en números y en fracciones de uso común, en el contexto de la resolución de problemas

### Datos y probabilidades

23. **OA 23.** Realizar encuestas, clasificar y organizar los datos obtenidos en tablas y visualizarlos en gráficos de barra.

24. **OA 24.** Registrar y ordenar datos obtenidos de juegos aleatorios con dados y monedas, encontrando el menor, el mayor y estimando el punto medio entre ambos.

25. **OA 25.** [Prioritario]{.change-badge .change-priority} Construir, leer e interpretar pictogramas y gráficos de barra simple con escala, de acuerdo a información recolectada o dada.

26. **OA 26.** Representar datos usando diagramas de puntos.

## 3.3.4 Cuarto básico

### Números y operaciones

1. **OA 1.** [Prioritario]{.change-badge .change-priority} Representar y describir números del 0 al 10000:

    - contándolos de 10 en 10, de 100 en 100, de 1000 en 1000

    - leyéndolos y escribiéndolos

    - representándolos en forma concreta, pictórica y simbólica

    - comparándolos y ordenándolos en la recta numérica o la tabla posicional

    - identificando el valor posicional de los dígitos hasta la decena de mil

    - componiendo y descomponiendo números naturales hasta 10000 en forma aditiva, de acuerdo a su valor posicional

2. **OA 2.** [Prioritario]{.change-badge .change-priority} Describir y aplicar estrategias de cálculo mental para determinar las multiplicaciones hasta $10\cdot 10$ y sus divisiones correspondientes:

    - conteo hacia delante y atrás

    - doblar y dividir por 2

    - por descomposición

    - usar el doble del doble

3. **OA 3.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la adición y la sustracción de números hasta 1000:

    - usando estrategias personales para realizar estas operaciones

    - descomponiendo los números involucrados

    - estimando sumas y diferencias

    - resolviendo problemas rutinarios y no rutinarios que incluyan adiciones y sustracciones

    - aplicando los algoritmos en la adición de hasta cuatro sumandos y en la sustracción de hasta un sustraendo

4. **OA 4.** Fundamentar y aplicar las propiedades del 0 y del 1 para la multiplicación y la propiedad del 1 para la división.

5. **OA 5.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la multiplicación de números de tres dígitos por números de un dígito:

    - usando estrategias con o sin material concreto

    - utilizando las tablas de multiplicación

    - estimando productos

    - usando la propiedad distributiva de la multiplicación respecto de la suma

    - aplicando el algoritmo de la multiplicación

    - resolviendo problemas rutinarios

6. **OA 6.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden la división con dividendos de dos dígitos y divisores de un dígito:

    - usando estrategias para dividir, con o sin material concreto

    - utilizando la relación que existe entre la división y la multiplicación

    - estimando el cociente

    - aplicando la estrategia por descomposición del dividendo

    - aplicando el algoritmo de la división

7. **OA 7.** [Prioritario]{.change-badge .change-priority} Resolver problemas rutinarios y no rutinarios en contextos cotidianos que incluyen dinero, seleccionando y utilizando la operación apropiada.

8. **OA 8.** [Prioritario]{.change-badge .change-priority} Demostrar que comprende las fracciones con denominadores 100, 12, 10, 8, 6, 5, 4, 3, 2:

    - explicando que una fracción representa la parte de un todo o de un grupo de elementos y un lugar en la recta numérica

    - describiendo situaciones en las cuales se puede usar fracciones

    - mostrando que una fracción puede tener representaciones diferentes

    - comparando y ordenando fracciones (por ejemplo: $\frac{1}{100}, \frac{1}{8}, \frac{1}{5}, \frac{1}{4}, \frac{1}{2}$) con material concreto y pictórico

9. **OA 9.** [Prioritario]{.change-badge .change-priority} Resolver adiciones y sustracciones de fracciones con igual denominador (denominadores 100, 12, 10, 8, 6, 5, 4, 3, 2) de manera concreta y pictórica en el contexto de la resolución de problemas.

10. **OA 10.** Identificar, escribir y representar fracciones propias y los números mixtos hasta el 5 de manera concreta, pictórica y simbólica, en el contexto de la resolución de problemas.

11. **OA 11.** Describir y representar decimales (décimos y centésimos):

    - representándolos en forma concreta, pictórica y simbólica, de manera manual y/o con *software* educativo

    - comparándolos y ordenándolos hasta la centésima

12. **OA 12.** Resolver adiciones y sustracciones de decimales, empleando el valor posicional hasta la centésima en el contexto de la resolución de problemas.

### Patrones y álgebra

13. **OA 13.** [Prioritario]{.change-badge .change-priority} Identificar y describir patrones numéricos en tablas que involucren una operación, de manera manual y/o usando software educativo.

14. **OA 14.** [Prioritario]{.change-badge .change-priority} Resolver ecuaciones e inecuaciones de un paso que involucren adiciones y sustracciones, comprobando los resultados en forma pictórica y simbólica del 0 al 100 y aplicando las relaciones inversas entre la adición y la sustracción.

### Geometría

15. **OA 15.** Describir la localización absoluta de un objeto en un mapa simple con coordenadas informales (por ejemplo: con letras y números) y la localización relativa con relación a otros objetos.

16. **OA 16.** Determinar las vistas de figuras 3D desde el frente, desde el lado y desde arriba.

17. **OA 17.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden una línea de simetría:

    - identificando figuras simétricas 2D

    - creando figuras simétricas 2D

    - dibujando una o más líneas de simetría en figuras 2D

    - usando *software* geométrico

18. **OA 18.** [Prioritario]{.change-badge .change-priority} Trasladar, rotar y reflejar figuras 2D.

19. **OA 19.** [Prioritario]{.change-badge .change-priority} Construir ángulos con el transportador y compararlos.

### Medición

20. **OA 20.** Leer y registrar diversas mediciones del tiempo en relojes análogos y digitales, usando los conceptos a. m., p. m. y 24 horas.

21. **OA 21.** Realizar conversiones entre unidades de tiempo en el contexto de la resolución de problemas: el número de segundos en un minuto, el número de minutos en una hora, el número de días en un mes y el número de meses en un año.

22. **OA 22.** [Prioritario]{.change-badge .change-priority} Medir longitudes con unidades estandarizadas (m, cm) y realizar transformaciones entre estas unidades (m a cm y viceversa) en el contexto de la resolución de problemas.

23. **OA 23.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden el concepto de área de un rectángulo y de un cuadrado:

    - reconociendo que el área de una superficie se mide en unidades cuadradas

    - seleccionando y justificando la elección de la unidad estandarizada (cm^2^ y m^2^)

    - determinando y registrando el área en cm^2^ y m^2^ en contextos cercanos

    - construyendo diferentes rectángulos para un área dada (cm^2^ y m^2^), para mostrar que distintos rectángulos pueden tener la misma área

    - usando *software* geométrico

24. **OA 24.** [Prioritario]{.change-badge .change-priority} Demostrar que comprenden el concepto de volumen de un cuerpo:

    - seleccionando una unidad no estandarizada para medir el volumen de un cuerpo

    - reconociendo que el volumen se mide en unidades de cubo

    - midiendo y registrando el volumen en unidades de cubo

    - usando *software* geométrico

### Datos y probabilidades

25. **OA 25.** [Prioritario]{.change-badge .change-priority} Realizar encuestas, analizar los datos y comparar con los resultados de muestras aleatorias, usando tablas y gráficos.

26. **OA 26.** Realizar experimentos aleatorios lúdicos y cotidianos, y tabular y representar mediante gráficos de manera manual y/o con *software* educativo.

27. **OA 27.** [Prioritario]{.change-badge .change-priority} Leer e interpretar pictogramas y gráficos de barra simple con escala y comunicar sus conclusiones.
